#!/usr/bin/env bash
# lab/vault.sh - create the lab's vault on first use: .vault_pass with a random
# vault password, and inventories/lab/group_vars/all/vault.yml with random
# passwords for Harbor and Nexus, encrypted. Leaves existing files alone.
set -euo pipefail
cd "$(dirname "$0")/.."
[[ -x .venv/bin/ansible-vault ]] && export PATH="$PWD/.venv/bin:$PATH"   # the lab's ansible-core
umask 077

VAULT=inventories/lab/group_vars/all/vault.yml
random() { openssl rand -base64 48 | tr -dc 'A-Za-z0-9' | cut -c1-"${1:-20}"; }

if [[ ! -s .vault_pass ]]; then
  random 40 > .vault_pass
  echo "Created .vault_pass (the lab's vault password; never committed)"
fi

if [[ ! -s "$VAULT" ]]; then
  cat > "$VAULT" <<VAULT
---
# The lab's secrets, generated by lab/vault.sh. View them with: make lab-info
vault_harbor_admin_password:  "Lab1$(random 16)"
vault_harbor_db_password:     "$(random 24)"
vault_repo_username:          "kit-read"
vault_repo_password:          "$(random 24)"
vault_nexus_admin_password:   "$(random 24)"
vault_nexus_upload_user:      "kit-upload"
vault_nexus_upload_password:  "$(random 24)"
VAULT
  ansible-vault encrypt --vault-password-file .vault_pass "$VAULT" >/dev/null
  echo "Created $VAULT (encrypted)"
fi
